### ISSUE TITLE
fails to build on 10.10.3

### ISSUE THREAD

**Issue by xtrntr** [osrf/homebrew-simulation#39] opened 2015-05-23 19:19 UTC
https://gist.github.com/anonymous/3cc5d2753cc45c3991d4

**Comment by scpeters** [comment] 2015-05-25 07:29
This was caused by the recent release of bullet 2.83 into homebrew. Gazebo 4-6 have been [fixed upstream](https://bitbucket.org/osrf/gazebo/pull-request/1664/support-bullet-283/diff), but not yet released with the fix. I had intended to apply a patch to the gazebo formulae once bullet 2.83 was merged, but I forgot. Thanks for the reminder!

I applied a patch in efcdb8a7cdee933064a0edc80933c93a741056a8; which should fix the problem. Please re-open if the problem persists.

**Closed by scpeters** 2015-05-25 07:29 UTC
