### ISSUE TITLE
Gazebo4 compilation fail

### ISSUE THREAD

**Issue by kt10aan** [osrf/homebrew-simulation#34] opened 2015-01-01 09:00 UTC
Gazebo4 fails to compile stopping around the 74-75% mark.

The full logs are here:
https://gist.github.com/anonymous/fb02091d83e713e479d9

Again, 2 weeks approximately ago, the formula was building fine.

**Comment by scpeters** [comment] 2015-01-01 09:54
The failure is caused by an interaction between boost 1.57 and the qt4 moc preprocessor. There is a [gazebo issue](https://bitbucket.org/osrf/gazebo/issue/1399/build-fails-with-boost-157) and some fixes in branches that are waiting for code review.

Thanks for the report!

**Comment by scpeters** [comment] 2015-01-08 13:03
gazebo4 formula fixed as of https://github.com/osrf/homebrew-simulation/commit/98e265acf34df57a61b7e499c60e142c702fd2ed

**Closed by scpeters** 2015-01-08 13:03 UTC
